#ifndef _CPPSETTINGSCMD_H
#define _CPPSETTINGSCMD_H


// Internal enum
enum CppSettingsCmd {
  getCppSettingsCmd,
  getCppUseDefaultsCmd,
  setCppUseDefaultsCmd,
  setCppTypeCmd,
  setCppRelationAttributeStereotypeCmd,
  setCppClassStereotypeCmd,
  setCppIncludeCmd,
  setCppHeaderContentCmd,
  setCppRootDirCmd,
  setCppSourceContentCmd,
  setCppHeaderExtensionCmd,
  setCppSourceExtensionCmd,
  setCppIncludeWithPathCmd,
  setCppEnumInCmd,
  setCppEnumOutCmd,
  setCppEnumInOutCmd,
  setCppInCmd,
  setCppOutCmd,
  setCppInOutCmd,
  setCppClassDeclCmd,
  setCppExternalClassDeclCmd,
  setCppStructDeclCmd,
  setCppUnionDeclCmd,
  setCppEnumDeclCmd,
  setCppTypedefDeclCmd,
  setCppAttributeDeclCmd,
  setCppEnumItemDeclCmd,
  setCppRelationDeclCmd,
  setCppOperationDeclCmd,
  setCppOperationDefCmd,
  setCppOperationForceThrowCmd,
  setCppGetVisibilityCmd,
  setCppGetNameCmd,
  setCppIsGetInlineCmd,
  setCppIsGetConstCmd,
  setCppIsGetValueConstCmd,
  setCppSetVisibilityCmd,
  setCppSetNameCmd,
  setCppIsSetInlineCmd,
  setCppIsSetParamConstCmd,
  setCppEnumReturnCmd,
  setCppReturnCmd,
  setCppIsSetParamRefCmd,
  setCppRelativePathCmd,
  setCppForceNamespaceGenCmd,
  setCppRootRelativePathCmd,
  setCppJavadocStyleCmd,
  setCppInlineOperForceInclInHeaderCmd,
  setCppDirRevFilterCmd,
  setCppFileRevFilterCmd,
  setCppIndentVisibilityCmd

};
#endif
